### PR TITLE
Fix compose containing a wrong space as initial reply text

### LINKED ISSUE #111: Compose text area always contains a space for replies
When replying, the initial text always gets set as `initialText=TextUtils.join(" ", mentions)+" ";`, even if `mentions` is empty. This is the case when adding a reply to one's own post.

Replying to others works fine; the initial text is set to e.g. "@Mastodon​@​mastodon.social ". Replying to oneself results in a single space as the initial text.

### PR DESCRIPTION
**Pull request by sk22**
Fixes #111

### CODE REVIEW

File: mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java [hunk 1]
```diff
@@ -449,7 +449,7 @@ public void afterTextChanged(Editable s){
 				if(!mentions.contains(m))
 					mentions.add(m);
 			}
-			initialText=TextUtils.join(" ", mentions)+" ";
+			initialText=mentions.isEmpty() ? "" : TextUtils.join(" ", mentions)+" ";
```
Comment (sk22) [inline mastodon/src/main/java/org/joinmastodon/android/fragments/ComposeFragment.java:452]: If the mentions string (containing e.g. "@Mastodon@mastodon.social") list is empty, use an empty string as the initial text, only otherwise join the mentions and add a single space after.
